version: '3.8'

services:
  uisp-bot:
    container_name: uisp-bot
    image: ghcr.io/52sadan97/uisp-auto-adopter:main
    # If building locally:
    # build: .
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      # Mount a local 'data' directory to the container's '/data' directory
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_DIR=/data
